# Generated by Django 4.2.6 on 2023-12-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_task_deadline_remove_task_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
